In [1]:
import os
import re
import numpy as np
import pandas as pd
from glob import glob
import math

In [2]:
BASE_DIR = "/users/6/mehta423/daycent/data/SAS_KGML_090925"
INPUT_DIR = os.path.join(BASE_DIR, "InputData")
OUTPUT_DIR = os.path.join(BASE_DIR, "OutputData_Synthetic_10000")
PROCESSED_DIR = "/users/6/mehta423/daycent/data/processed"

WEATHER_DIR = os.path.join(INPUT_DIR, "WeatherData")
INITC_FN = os.path.join(INPUT_DIR, "initial_site_conditions.xlsx")

MONTHLY_FN = os.path.join(OUTPUT_DIR, "SAS_scenario_1_monthly.csv")
HARVEST_FN = os.path.join(OUTPUT_DIR, "SAS_scenario_1_harvest.csv")

SCENARIOS_FN = os.path.join(INPUT_DIR, "schedule_scenarios_all_Synthetic_10000.csv")

In [3]:
all_points = []

for points in os.listdir(WEATHER_DIR):
    df = pd.read_csv(os.path.join(WEATHER_DIR, points))
    df['point_id'] = points.split(".csv")[0]
    all_points.append(df)

weather_df = pd.concat(all_points, ignore_index=True)
weather_df.head()

   Year  doy   Tmax  Tmin  Precip point_id
0  2000    1   5.27 -4.83   0.000  1773513
1  2000    2  12.73 -1.85   0.000  1773513
2  2000    3  15.02  2.43   0.052  1773513
3  2000    4  10.48  0.62   1.026  1773513
4  2000    5   1.87 -5.29   0.041  1773513

In [4]:
# vocabulary of management events
MANAGEMENT_CLASSES = [
 'conventional_till_molboadplow','herbicide','soybean_planting',
 'nitrogen_fertilization_1.5gNm2','harvest_grain','cycle_end',
 'ryegrass_planting','nitrogen_fertilization_0gNm2',
 'reduced_till_tandemdisk','notill_rodweederrow','corn_planting',
 'nitrogen_fertilization_17.74gNm2','winterwheat_planting',
 'nitrogen_fertilization_10.312gNm2'
]

scenarios_df = pd.read_csv(SCENARIOS_FN)
scenarios_df = scenarios_df.rename({'simyear': 'Year'},  axis=1)

scenarios_df = scenarios_df.pivot_table(
    index=['scenario', 'Year', 'doy'], # Use all identifying columns for the index
    columns='management',
    aggfunc='size',
    fill_value=0
).reset_index()

# scenarios_df = scenarios_df[scenarios_df['scenario'] == 'scenario_1']
print(scenarios_df)

management       scenario  Year  doy  conventional_till_molboadplow  \
0              scenario_1  2000  132                              1
1              scenario_1  2000  136                              0
2              scenario_1  2000  137                              0
3              scenario_1  2000  289                              0
4              scenario_1  2000  294                              1
...                   ...   ...  ...                            ...
1086445     scenario_9999  2023  129                              0
1086446     scenario_9999  2023  130                              0
1086447     scenario_9999  2023  305                              0
1086448     scenario_9999  2023  310                              0
1086449     scenario_9999  2023  315                              0

management  corn_planting  cycle_end  harvest_grain  herbicide  \
0                       0          0              0          0
1                       0          0              0          1
2                       0          0              0          0
3                       0          1              1          0
4                       0          0              0          0
...                   ...        ...            ...        ...
1086445                 0          0              0          1
1086446                 1          0              0          0
1086447                 0          1              1          0
1086448                 0          0              0          0
1086449                 0          0              0          0

management  nitrogen_fertilization_0gNm2  nitrogen_fertilization_1.5gNm2  \
0                                      0                               0
1                                      0                               0
2                                      0                               1
3                                      0                               0
4                                      0                               0
...                                  ...                             ...
1086445                                0                               0
1086446                                0                               0
1086447                                0                               0
1086448                                0                               0
1086449                                0                               0

management  nitrogen_fertilization_10.312gNm2  \
0                                           0
1                                           0
2                                           0
3                                           0
4                                           0
...                                       ...
1086445                                     0
1086446                                     0
1086447                                     0
1086448                                     0
1086449                                     1

management  nitrogen_fertilization_17.74gNm2  notill_rodweederrow  \
0                                          0                    0
1                                          0                    0
2                                          0                    0
3                                          0                    0
4                                          0                    0
...                                      ...                  ...
1086445                                    0                    0
1086446                                    1                    0
1086447                                    0                    0
1086448                                    0                    1
1086449                                    0                    0

management  reduced_till_tandemdisk  ryegrass_planting  soybean_planting  \
0                                 0                  0                 0
1                                 0                  0                 0
2                                 0                  0                 1
3                                 0                  0                 0
4                                 0                  0                 0
...                             ...                ...               ...
1086445                           0                  0                 0
1086446                           0                  0                 0
1086447                           0                  0                 0
1086448                           0                  0                 0
1086449                           0                  0                 0

management  winterwheat_planting
0                              0
1                              0
2                              0
3                              0
4                              0
...                          ...
1086445                        0
1086446                        0
1086447                        0
1086448                        0
1086449                        1

[1086450 rows x 17 columns]

In [7]:
X_daily = pd.merge(weather_df, scenarios_df, on=['Year', 'doy'], how='left')
X_daily.drop(columns=['scenario'], inplace=True)
X_daily.fillna(0, inplace=True)
X_daily

:

:

In [17]:
X_daily.isna().sum()

Year                                 0
doy                                  0
Tmax                                 0
Tmin                                 0
Precip                               0
point_id                             0
conventional_till_molboadplow        0
corn_planting                        0
cycle_end                            0
harvest_grain                        0
herbicide                            0
nitrogen_fertilization_0gNm2         0
nitrogen_fertilization_1.5gNm2       0
nitrogen_fertilization_10.312gNm2    0
nitrogen_fertilization_17.74gNm2     0
notill_rodweederrow                  0
reduced_till_tandemdisk              0
ryegrass_planting                    0
soybean_planting                     0
winterwheat_planting                 0
dtype: int64

In [7]:


files = os.listdir(OUTPUT_DIR)

pattern = re.compile(r"scenario_(\d+)")

numbers = sorted({(match.group(1)) for f in files if (match := pattern.search(f))})
print(numbers)

['1', '10', '100', '1000', '10000', '1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '101', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '102', '1020', '1021', '1022', '1023', '1024', '1025', '1026', '1027', '1028', '1029', '103', '1030', '1031', '1032', '1033', '1034', '1035', '1036', '1037', '1038', '1039', '104', '1040', '1041', '1042', '1043', '1044', '1045', '1046', '1047', '1048', '1049', '105', '1050', '1051', '1052', '1053', '1054', '1055', '1056', '1057', '1058', '1059', '106', '1060', '1061', '1062', '1063', '1064', '1065', '1066', '1067', '1068', '1069', '107', '1070', '1071', '1072', '1073', '1074', '1075', '1076', '1077', '1078', '1079', '108', '1080', '1081', '1082', '1083', '1084', '1085', '1086', '1087', '1088', '1089', '109', '1090', '1091', '1092', '1093', '1094', '1095', '1096', '1097', '1098', '1099', '11', '110', '1100', '1101', '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109', '111', '1110', '1111', '1112', '1113', '1114', '1115', '1116', '1117', '1118', '1119', '112', '1120', '1121', '1122', '1123', '1124', '1125', '1126', '1127', '1128', '1129', '113', '1130', '1131', '1132', '1133', '1134', '1135', '1136', '1137', '1138', '1139', '114', '1140', '1141', '1142', '1143', '1144', '1145', '1146', '1147', '1148', '1149', '115', '1150', '1151', '1152', '1153', '1154', '1155', '1156', '1157', '1158', '1159', '116', '1160', '1161', '1162', '1163', '1164', '1165', '1166', '1167', '1168', '1169', '117', '1170', '1171', '1172', '1173', '1174', '1175', '1176', '1177', '1178', '1179', '118', '1180', '1181', '1182', '1183', '1184', '1185', '1186', '1187', '1188', '1189', '119', '1190', '1191', '1192', '1193', '1194', '1195', '1196', '1197', '1198', '1199', '12', '120', '1200', '1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208', '1209', '121', '1210', '1211', '1212', '1213', '1214', '1215', '1216', '1217', '1218', '1219', '122', '1220', '1221', '1222', '1223', '1224', '1225', '1226', '1227', '1228', '1229', '123', '1230', '1231', '1232', '1233', '1234', '1235', '1236', '1237', '1238', '1239', '124', '1240', '1241', '1242', '1243', '1244', '1245', '1246', '1247', '1248', '1249', '125', '1250', '1251', '1252', '1253', '1254', '1255', '1256', '1257', '1258', '1259', '126', '1260', '1261', '1262', '1263', '1264', '1265', '1266', '1267', '1268', '1269', '127', '1270', '1271', '1272', '1273', '1274', '1275', '1276', '1277', '1278', '1279', '128', '1280', '1281', '1282', '1283', '1284', '1285', '1286', '1287', '1288', '1289', '129', '1290', '1291', '1292', '1293', '1294', '1295', '1296', '1297', '1298', '1299', '13', '130', '1300', '1301', '1302', '1303', '1304', '1305', '1306', '1307', '1308', '1309', '131', '1310', '1311', '1312', '1313', '1314', '1315', '1316', '1317', '1318', '1319', '132', '1320', '1321', '1322', '1323', '1324', '1325', '1326', '1327', '1328', '1329', '133', '1330', '1331', '1332', '1333', '1334', '1335', '1336', '1337', '1338', '1339', '134', '1340', '1341', '1342', '1343', '1344', '1345', '1346', '1347', '1348', '1349', '135', '1350', '1351', '1352', '1353', '1354', '1355', '1356', '1357', '1358', '1359', '136', '1360', '1361', '1362', '1363', '1364', '1365', '1366', '1367', '1368', '1369', '137', '1370', '1371', '1372', '1373', '1374', '1375', '1376', '1377', '1378', '1379', '138', '1380', '1381', '1382', '1383', '1384', '1385', '1386', '1387', '1388', '1389', '139', '1390', '1391', '1392', '1393', '1394', '1395', '1396', '1397', '1398', '1399', '14', '140', '1400', '1401', '1402', '1403', '1404', '1405', '1406', '1407', '1408', '1409', '141', '1410', '1411', '1412', '1413', '1414', '1415', '1416', '1417', '1418', '1419', '142', '1420', '1421', '1422', '1423', '1424', '1425', '1426', '1427', '1428', '1429', '143', '1430', '1431', '1432', '1433', '1434', '1435', '1436', '1437', '1438', '1439', '144', '1440', '1441', '1442', '1443', '1444', '1445', '1446', '1447', '1448', '1449', '145', '1450', '1451', '1452', '1453', '1454', '1455', '1456', '1457', '1458', '1459', '146', '1460', '1461', '1462', '1463', '1464', '1465', '1466', '1467', '1468', '1469', '147', '1470', '1471', '1472', '1473', '1474', '1475', '1476', '1477', '1478', '1479', '148', '1480', '1481', '1482', '1483', '1484', '1485', '1486', '1487', '1488', '1489', '149', '1490', '1491', '1492', '1493', '1494', '1495', '1496', '1497', '1498', '1499', '15', '150', '1500', '1501', '1502', '1503', '1504', '1505', '1506', '1507', '1508', '1509', '151', '1510', '1511', '1512', '1513', '1514', '1515', '1516', '1517', '1518', '1519', '152', '1520', '1521', '1522', '1523', '1524', '1525', '1526', '1527', '1528', '1529', '153', '1530', '1531', '1532', '1533', '1534', '1535', '1536', '1537', '1538', '1539', '154', '1540', '1541', '1542', '1543', '1544', '1545', '1546', '1547', '1548', '1549', '155', '1550', '1551', '1552', '1553', '1554', '1555', '1556', '1557', '1558', '1559', '156', '1560', '1561', '1562', '1563', '1564', '1565', '1566', '1567', '1568', '1569', '157', '1570', '1571', '1572', '1573', '1574', '1575', '1576', '1577', '1578', '1579', '158', '1580', '1581', '1582', '1583', '1584', '1585', '1586', '1587', '1588', '1589', '159', '1590', '1591', '1592', '1593', '1594', '1595', '1596', '1597', '1598', '1599', '16', '160', '1600', '1601', '1602', '1603', '1604', '1605', '1606', '1607', '1608', '1609', '161', '1610', '1611', '1612', '1613', '1614', '1615', '1616', '1617', '1618', '1619', '162', '1620', '1621', '1622', '1623', '1624', '1625', '1626', '1627', '1628', '1629', '163', '1630', '1631', '1632', '1633', '1634', '1635', '1636', '1637', '1638', '1639', '164', '1640', '1641', '1642', '1643', '1644', '1645', '1646', '1647', '1648', '1649', '165', '1650', '1651', '1652', '1653', '1654', '1655', '1656', '1657', '1658', '1659', '166', '1660', '1661', '1662', '1663', '1664', '1665', '1666', '1667', '1668', '1669', '167', '1670', '1671', '1672', '1673', '1674', '1675', '1676', '1677', '1678', '1679', '168', '1680', '1681', '1682', '1683', '1684', '1685', '1686', '1687', '1688', '1689', '169', '1690', '1691', '1692', '1693', '1694', '1695', '1696', '1697', '1698', '1699', '17', '170', '1700', '1701', '1702', '1703', '1704', '1705', '1706', '1707', '1708', '1709', '171', '1710', '1711', '1712', '1713', '1714', '1715', '1716', '1717', '1718', '1719', '172', '1720', '1721', '1722', '1723', '1724', '1725', '1726', '1727', '1728', '1729', '173', '1730', '1731', '1732', '1733', '1734', '1735', '1736', '1737', '1738', '1739', '174', '1740', '1741', '1742', '1743', '1744', '1745', '1746', '1747', '1748', '1749', '175', '1750', '1751', '1752', '1753', '1754', '1755', '1756', '1757', '1758', '1759', '176', '1760', '1761', '1762', '1763', '1764', '1765', '1766', '1767', '1768', '1769', '177', '1770', '1771', '1772', '1773', '1774', '1775', '1776', '1777', '1778', '1779', '178', '1780', '1781', '1782', '1783', '1784', '1785', '1786', '1787', '1788', '1789', '179', '1790', '1791', '1792', '1793', '1794', '1795', '1796', '1797', '1798', '1799', '18', '180', '1800', '1801', '1802', '1803', '1804', '1805', '1806', '1807', '1808', '1809', '181', '1810', '1811', '1812', '1813', '1814', '1815', '1816', '1817', '1818', '1819', '182', '1820', '1821', '1822', '1823', '1824', '1825', '1826', '1827', '1828', '1829', '183', '1830', '1831', '1832', '1833', '1834', '1835', '1836', '1837', '1838', '1839', '184', '1840', '1841', '1842', '1843', '1844', '1845', '1846', '1847', '1848', '1849', '185', '1850', '1851', '1852', '1853', '1854', '1855', '1856', '1857', '1858', '1859', '186', '1860', '1861', '1862', '1863', '1864', '1865', '1866', '1867', '1868', '1869', '187', '1870', '1871', '1872', '1873', '1874', '1875', '1876', '1877', '1878', '1879', '188', '1880', '1881', '1882', '1883', '1884', '1885', '1886', '1887', '1888', '1889', '189', '1890', '1891', '1892', '1893', '1894', '1895', '1896', '1897', '1898', '1899', '19', '190', '1900', '1901', '1902', '1903', '1904', '1905', '1906', '1907', '1908', '1909', '191', '1910', '1911', '1912', '1913', '1914', '1915', '1916', '1917', '1918', '1919', '192', '1920', '1921', '1922', '1923', '1924', '1925', '1926', '1927', '1928', '1929', '193', '1930', '1931', '1932', '1933', '1934', '1935', '1936', '1937', '1938', '1939', '194', '1940', '1941', '1942', '1943', '1944', '1945', '1946', '1947', '1948', '1949', '195', '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957', '1958', '1959', '196', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '197', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '198', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '199', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2', '20', '200', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '201', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '202', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '203', '2030', '2031', '2032', '2033', '2034', '2035', '2036', '2037', '2038', '2039', '204', '2040', '2041', '2042', '2043', '2044', '2045', '2046', '2047', '2048', '2049', '205', '2050', '2051', '2052', '2053', '2054', '2055', '2056', '2057', '2058', '2059', '206', '2060', '2061', '2062', '2063', '2064', '2065', '2066', '2067', '2068', '2069', '207', '2070', '2071', '2072', '2073', '2074', '2075', '2076', '2077', '2078', '2079', '208', '2080', '2081', '2082', '2083', '2084', '2085', '2086', '2087', '2088', '2089', '209', '2090', '2091', '2092', '2093', '2094', '2095', '2096', '2097', '2098', '2099', '21', '210', '2100', '2101', '2102', '2103', '2104', '2105', '2106', '2107', '2108', '2109', '211', '2110', '2111', '2112', '2113', '2114', '2115', '2116', '2117', '2118', '2119', '212', '2120', '2121', '2122', '2123', '2124', '2125', '2126', '2127', '2128', '2129', '213', '2130', '2131', '2132', '2133', '2134', '2135', '2136', '2137', '2138', '2139', '214', '2140', '2141', '2142', '2143', '2144', '2145', '2146', '2147', '2148', '2149', '215', '2150', '2151', '2152', '2153', '2154', '2155', '2156', '2157', '2158', '2159', '216', '2160', '2161', '2162', '2163', '2164', '2165', '2166', '2167', '2168', '2169', '217', '2170', '2171', '2172', '2173', '2174', '2175', '2176', '2177', '2178', '2179', '218', '2180', '2181', '2182', '2183', '2184', '2185', '2186', '2187', '2188', '2189', '219', '2190', '2191', '2192', '2193', '2194', '2195', '2196', '2197', '2198', '2199', '22', '220', '2200', '2201', '2202', '2203', '2204', '2205', '2206', '2207', '2208', '2209', '221', '2210', '2211', '2212', '2213', '2214', '2215', '2216', '2217', '2218', '2219', '222', '2220', '2221', '2222', '2223', '2224', '2225', '2226', '2227', '2228', '2229', '223', '2230', '2231', '2232', '2233', '2234', '2235', '2236', '2237', '2238', '2239', '224', '2240', '2241', '2242', '2243', '2244', '2245', '2246', '2247', '2248', '2249', '225', '2250', '2251', '2252', '2253', '2254', '2255', '2256', '2257', '2258', '2259', '226', '2260', '2261', '2262', '2263', '2264', '2265', '2266', '2267', '2268', '2269', '227', '2270', '2271', '2272', '2273', '2274', '2275', '2276', '2277', '2278', '2279', '228', '2280', '2281', '2282', '2283', '2284', '2285', '2286', '2287', '2288', '2289', '229', '2290', '2291', '2292', '2293', '2294', '2295', '2296', '2297', '2298', '2299', '23', '230', '2300', '2301', '2302', '2303', '2304', '2305', '2306', '2307', '2308', '2309', '231', '2310', '2311', '2312', '2313', '2314', '2315', '2316', '2317', '2318', '2319', '232', '2320', '2321', '2322', '2323', '2324', '2325', '2326', '2327', '2328', '2329', '233', '2330', '2331', '2332', '2333', '2334', '2335', '2336', '2337', '2338', '2339', '234', '2340', '2341', '2342', '2343', '2344', '2345', '2346', '2347', '2348', '2349', '235', '2350', '2351', '2352', '2353', '2354', '2355', '2356', '2357', '2358', '2359', '236', '2360', '2361', '2362', '2363', '2364', '2365', '2366', '2367', '2368', '2369', '237', '2370', '2371', '2372', '2373', '2374', '2375', '2376', '2377', '2378', '2379', '238', '2380', '2381', '2382', '2383', '2384', '2385', '2386', '2387', '2388', '2389', '239', '2390', '2391', '2392', '2393', '2394', '2395', '2396', '2397', '2398', '2399', '24', '240', '2400', '2401', '2402', '2403', '2404', '2405', '2406', '2407', '2408', '2409', '241', '2410', '2411', '2412', '2413', '2414', '2415', '2416', '2417', '2418', '2419', '242', '2420', '2421', '2422', '2423', '2424', '2425', '2426', '2427', '2428', '2429', '243', '2430', '2431', '2432', '2433', '2434', '2435', '2436', '2437', '2438', '2439', '244', '2440', '2441', '2442', '2443', '2444', '2445', '2446', '2447', '2448', '2449', '245', '2450', '2451', '2452', '2453', '2454', '2455', '2456', '2457', '2458', '2459', '246', '2460', '2461', '2462', '2463', '2464', '2465', '2466', '2467', '2468', '2469', '247', '2470', '2471', '2472', '2473', '2474', '2475', '2476', '2477', '2478', '2479', '248', '2480', '2481', '2482', '2483', '2484', '2485', '2486', '2487', '2488', '2489', '249', '2490', '2491', '2492', '2493', '2494', '2495', '2496', '2497', '2498', '2499', '25', '250', '2500', '2501', '2502', '2503', '2504', '2505', '2506', '2507', '2508', '2509', '251', '2510', '2511', '2512', '2513', '2514', '2515', '2516', '2517', '2518', '2519', '252', '2520', '2521', '2522', '2523', '2524', '2525', '2526', '2527', '2528', '2529', '253', '2530', '2531', '2532', '2533', '2534', '2535', '2536', '2537', '2538', '2539', '254', '2540', '2541', '2542', '2543', '2544', '2545', '2546', '2547', '2548', '2549', '255', '2550', '2551', '2552', '2553', '2554', '2555', '2556', '2557', '2558', '2559', '256', '2560', '2561', '2562', '2563', '2564', '2565', '2566', '2567', '2568', '2569', '257', '2570', '2571', '2572', '2573', '2574', '2575', '2576', '2577', '2578', '2579', '258', '2580', '2581', '2582', '2583', '2584', '2585', '2586', '2587', '2588', '2589', '259', '2590', '2591', '2592', '2593', '2594', '2595', '2596', '2597', '2598', '2599', '26', '260', '2600', '2601', '2602', '2603', '2604', '2605', '2606', '2607', '2608', '2609', '261', '2610', '2611', '2612', '2613', '2614', '2615', '2616', '2617', '2618', '2619', '262', '2620', '2621', '2622', '2623', '2624', '2625', '2626', '2627', '2628', '2629', '263', '2630', '2631', '2632', '2633', '2634', '2635', '2636', '2637', '2638', '2639', '264', '2640', '2641', '2642', '2643', '2644', '2645', '2646', '2647', '2648', '2649', '265', '2650', '2651', '2652', '2653', '2654', '2655', '2656', '2657', '2658', '2659', '266', '2660', '2661', '2662', '2663', '2664', '2665', '2666', '2667', '2668', '2669', '267', '2670', '2671', '2672', '2673', '2674', '2675', '2676', '2677', '2678', '2679', '268', '2680', '2681', '2682', '2683', '2684', '2685', '2686', '2687', '2688', '2689', '269', '2690', '2691', '2692', '2693', '2694', '2695', '2696', '2697', '2698', '2699', '27', '270', '2700', '2701', '2702', '2703', '2704', '2705', '2706', '2707', '2708', '2709', '271', '2710', '2711', '2712', '2713', '2714', '2715', '2716', '2717', '2718', '2719', '272', '2720', '2721', '2722', '2723', '2724', '2725', '2726', '2727', '2728', '2729', '273', '2730', '2731', '2732', '2733', '2734', '2735', '2736', '2737', '2738', '2739', '274', '2740', '2741', '2742', '2743', '2744', '2745', '2746', '2747', '2748', '2749', '275', '2750', '2751', '2752', '2753', '2754', '2755', '2756', '2757', '2758', '2759', '276', '2760', '2761', '2762', '2763', '2764', '2765', '2766', '2767', '2768', '2769', '277', '2770', '2771', '2772', '2773', '2774', '2775', '2776', '2777', '2778', '2779', '278', '2780', '2781', '2782', '2783', '2784', '2785', '2786', '2787', '2788', '2789', '279', '2790', '2791', '2792', '2793', '2794', '2795', '2796', '2797', '2798', '2799', '28', '280', '2800', '2801', '2802', '2803', '2804', '2805', '2806', '2807', '2808', '2809', '281', '2810', '2811', '2812', '2813', '2814', '2815', '2816', '2817', '2818', '2819', '282', '2820', '2821', '2822', '2823', '2824', '2825', '2826', '2827', '2828', '2829', '283', '2830', '2831', '2832', '2833', '2834', '2835', '2836', '2837', '2838', '2839', '284', '2840', '2841', '2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '285', '2850', '2851', '2852', '2853', '2854', '2855', '2856', '2857', '2858', '2859', '286', '2860', '2861', '2862', '2863', '2864', '2865', '2866', '2867', '2868', '2869', '287', '2870', '2871', '2872', '2873', '2874', '2875', '2876', '2877', '2878', '2879', '288', '2880', '2881', '2882', '2883', '2884', '2885', '2886', '2887', '2888', '2889', '289', '2890', '2891', '2892', '2893', '2894', '2895', '2896', '2897', '2898', '2899', '29', '290', '2900', '2901', '2902', '2903', '2904', '2905', '2906', '2907', '2908', '2909', '291', '2910', '2911', '2912', '2913', '2914', '2915', '2916', '2917', '2918', '2919', '292', '2920', '2921', '2922', '2923', '2924', '2925', '2926', '2927', '2928', '2929', '293', '2930', '2931', '2932', '2933', '2934', '2935', '2936', '2937', '2938', '2939', '294', '2940', '2941', '2942', '2943', '2944', '2945', '2946', '2947', '2948', '2949', '295', '2950', '2951', '2952', '2953', '2954', '2955', '2956', '2957', '2958', '2959', '296', '2960', '2961', '2962', '2963', '2964', '2965', '2966', '2967', '2968', '2969', '297', '2970', '2971', '2972', '2973', '2974', '2975', '2976', '2977', '2978', '2979', '298', '2980', '2981', '2982', '2983', '2984', '2985', '2986', '2987', '2988', '2989', '299', '2990', '2991', '2992', '2993', '2994', '2995', '2996', '2997', '2998', '2999', '3', '30', '300', '3000', '3001', '3002', '3003', '3004', '3005', '3006', '3007', '3008', '3009', '301', '3010', '3011', '3012', '3013', '3014', '3015', '3016', '3017', '3018', '3019', '302', '3020', '3021', '3022', '3023', '3024', '3025', '3026', '3027', '3028', '3029', '303', '3030', '3031', '3032', '3033', '3034', '3035', '3036', '3037', '3038', '3039', '304', '3040', '3041', '3042', '3043', '3044', '3045', '3046', '3047', '3048', '3049', '305', '3050', '3051', '3052', '3053', '3054', '3055', '3056', '3057', '3058', '3059', '306', '3060', '3061', '3062', '3063', '3064', '3065', '3066', '3067', '3068', '3069', '307', '3070', '3071', '3072', '3073', '3074', '3075', '3076', '3077', '3078', '3079', '308', '3080', '3081', '3082', '3083', '3084', '3085', '3086', '3087', '3088', '3089', '309', '3090', '3091', '3092', '3093', '3094', '3095', '3096', '3097', '3098', '3099', '31', '310', '3100', '3101', '3102', '3103', '3104', '3105', '3106', '3107', '3108', '3109', '311', '3110', '3111', '3112', '3113', '3114', '3115', '3116', '3117', '3118', '3119', '312', '3120', '3121', '3122', '3123', '3124', '3125', '3126', '3127', '3128', '3129', '313', '3130', '3131', '3132', '3133', '3134', '3135', '3136', '3137', '3138', '3139', '314', '3140', '3141', '3142', '3143', '3144', '3145', '3146', '3147', '3148', '3149', '315', '3150', '3151', '3152', '3153', '3154', '3155', '3156', '3157', '3158', '3159', '316', '3160', '3161', '3162', '3163', '3164', '3165', '3166', '3167', '3168', '3169', '317', '3170', '3171', '3172', '3173', '3174', '3175', '3176', '3177', '3178', '3179', '318', '3180', '3181', '3182', '3183', '3184', '3185', '3186', '3187', '3188', '3189', '319', '3190', '3191', '3192', '3193', '3194', '3195', '3196', '3197', '3198', '3199', '32', '320', '3200', '3201', '3202', '3203', '3204', '3205', '3206', '3207', '3208', '3209', '321', '3210', '3211', '3212', '3213', '3214', '3215', '3216', '3217', '3218', '3219', '322', '3220', '3221', '3222', '3223', '3224', '3225', '3226', '3227', '3228', '3229', '323', '3230', '3231', '3232', '3233', '3234', '3235', '3236', '3237', '3238', '3239', '324', '3240', '3241', '3242', '3243', '3244', '3245', '3246', '3247', '3248', '3249', '325', '3250', '3251', '3252', '3253', '3254', '3255', '3256', '3257', '3258', '3259', '326', '3260', '3261', '3262', '3263', '3264', '3265', '3266', '3267', '3268', '3269', '327', '3270', '3271', '3272', '3273', '3274', '3275', '3276', '3277', '3278', '3279', '

In [8]:
def load_output_data(scenario_ids: list[str]):
    all_outputs = []
    month_to_doy = {1:30, 2:58, 3:89, 4:119, 5:150, 6:180, 7:211, 8:242, 9:272, 10:303, 11:333, 12:364}

    for scenario_id in scenario_ids:
        monthly_df = pd.read_csv(os.path.join(OUTPUT_DIR, f"SAS_scenario_{scenario_id}_monthly.csv"))
        monthly_df = monthly_df.rename({'id': 'point_id'}, axis=1)
        monthly_df['doy'] = monthly_df['month'].map(month_to_doy)
        monthly_df['simyear'] = monthly_df['simyear'].apply(lambda x: math.floor(float(x)))

        harvest_df = pd.read_csv(os.path.join(OUTPUT_DIR, f"SAS_scenario_{scenario_id}_harvest.csv"))
        harvest_df = harvest_df.rename({'id': 'point_id', 'dayofyr': 'doy'}, axis=1)

        output_df = pd.merge(monthly_df, harvest_df, on=['runid', 'point_id', 'simyear', 'doy'], how='outer')
        output_df = output_df.rename({'simyear': 'Year'}, axis=1)
        output_df['point_id'] = output_df['point_id'].astype(str)

        dates = pd.to_datetime(output_df['Year'].astype(str) + '-' + output_df['doy'].astype(str), format='%Y-%j')
        output_df['month'].fillna(dates.dt.month, inplace=True)
        output_df['month'] = output_df['month'].astype(int)

        output_df.sort_values(['point_id', 'Year', 'month', 'doy'], inplace=True)
        output_df.sort_index(inplace=True)

        output_df['scenario_id'] = scenario_id  # keep track of scenario
        all_outputs.append(output_df)

    return pd.concat(all_outputs, ignore_index=True)


def load_management_data(scenario_ids: list[str]):
    scenarios_df = pd.read_csv(SCENARIOS_FN).rename({'simyear': 'Year'}, axis=1)

    scenarios_df = scenarios_df.pivot_table(
        index=['scenario', 'Year', 'doy'],
        columns='management',
        aggfunc='size',
        fill_value=0
    ).reset_index()

    # filter for only requested scenarios
    scenarios_df = scenarios_df[scenarios_df['scenario'].isin([f'scenario_{sid}' for sid in scenario_ids])]
    scenarios_df['scenario_id'] = scenarios_df['scenario'].str.replace('scenario_', '', regex=False)

    return scenarios_df


def load_data(scenario_ids: list[str], weather_df: pd.DataFrame):
    print("Loading management data...")
    management_df = load_management_data(scenario_ids)

    X_daily = pd.merge(weather_df, management_df, on=['Year', 'doy'], how='left')
    X_daily.fillna(0, inplace=True)

    print("Loading output data...")
    Y = load_output_data(scenario_ids)

    return X_daily, Y


# Example usage:
X_daily, Y = load_data(numbers, weather_df)

print(X_daily.head())
print(Y.head())

Loading management data...
Loading output data...

/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  output_df['month'].fillna(dates.dt.month, inplace=True)
/tmp/ipykernel_166034/752612133.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


FileNotFoundError: [Errno 2] No such file or directory: '/users/6/mehta423/daycent/data/SAS_KGML_090925/OutputData_Synthetic_10000/SAS_scenario_5398_monthly.csv'

In [ ]:
X_daily.to_csv(os.path.join(PROCESSED_DIR, "X_daily.csv"), index=False)
Y.to_csv(os.path.join(PROCESSED_DIR, "Y.csv"), index=False)

In [19]:
X_daily

,Year,doy,Tmax,Tmin,Precip,point_id,conventional_till_molboadplow,corn_planting,cycle_end,harvest_grain,herbicide,nitrogen_fertilization_0gNm2,nitrogen_fertilization_1.5gNm2,nitrogen_fertilization_10.312gNm2,nitrogen_fertilization_17.74gNm2,notill_rodweederrow,reduced_till_tandemdisk,ryegrass_planting,soybean_planting,winterwheat_planting
0,2000,1,5.270,-4.830,0.0000,1773513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2000,2,12.730,-1.850,0.0000,1773513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2000,3,15.020,2.430,0.0520,1773513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2000,4,10.480,0.620,1.0260,1773513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2000,5,1.870,-5.290,0.0410,1773513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1853791,2024,362,12.818,-2.313,0.8766,710977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1853792,2024,363,0.784,-5.354,0.0000,710977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1853793,2024,364,4.451,-5.468,0.0062,710977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1853794,2024,365,3.933,-3.492,0.1565,710977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1853795,2024,366,2.129,-4.846,0.0000,710977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
Y

       runid point_id  Year  month    somsc  doy   cgrain
0          1   657200  2000     10      NaN  289  170.656
1          1   657200  2001      1  5051.21   30      NaN
2          1   657200  2001      2  5050.51   58      NaN
3          1   657200  2001      3  5050.71   89      NaN
4          1   657200  2001      4  5051.53  119      NaN
...      ...      ...   ...    ...      ...  ...      ...
59068    203  1799675  2023     10      NaN  289  175.356
59069    203  1799675  2023     10  5606.59  303      NaN
59070    203  1799675  2023     11  5606.73  333      NaN
59071    203  1799675  2023     12  5603.19  364      NaN
59072    203  1799675  2024      1  5603.23   30      NaN

[59073 rows x 7 columns]

# Preprocessing

## Imputs processing

In [ ]:

df = X_daily

# Step 1: Drop leap day (doy == 366)
df = df[df["doy"] <= 365]
df = df.sort_values(by=["point_id", "Year", "doy"])

# Step 2: Select feature columns (include doy, exclude Year & point_id)
feature_cols = [c for c in df.columns if c not in ["Year", "point_id"]]

# Step 3: Group by point_id and Year
groups = df.groupby(["point_id", "Year"])

# Step 4: Create sequences and store mapping
sequences = []
mapping = []  # to store (point_id, year) for each sequence

for (pid, year), group in groups:
    if len(group) == 365:
        sequences.append(group[feature_cols].to_numpy())
        mapping.append((pid, year))  # store mapping info

# Convert to arrays
sequences = np.stack(sequences)  # shape: (num_sequences, 365, num_features)
mapping = np.array(mapping)      # shape: (num_sequences, 2)

# Step 5: Save both sequences and mapping
# Step 5: Save everything into one npy file
data_dict = {
    "data": sequences,
    "mapping": mapping,
    "columns": feature_cols
}

np.save(os.path.join(PROCESSED_DIR, "daycent_inputs.npy"), data_dict, allow_pickle=True)

In [22]:
feature_cols

['doy',
 'Tmax',
 'Tmin',
 'Precip',
 'conventional_till_molboadplow',
 'corn_planting',
 'cycle_end',
 'harvest_grain',
 'herbicide',
 'nitrogen_fertilization_0gNm2',
 'nitrogen_fertilization_1.5gNm2',
 'nitrogen_fertilization_10.312gNm2',
 'nitrogen_fertilization_17.74gNm2',
 'notill_rodweederrow',
 'reduced_till_tandemdisk',
 'ryegrass_planting',
 'soybean_planting',
 'winterwheat_planting']

In [13]:
sequences.shape

(5075, 365, 18)

In [15]:
# mapping = np.load("sequence_mapping.npy")
print(mapping[0])  # [point_id, Year] for first sequence

['1773513' '2000']

In [26]:
Y

       runid point_id  Year  month    somsc  doy   cgrain
0          1   657200  2000     10      NaN  289  170.656
1          1   657200  2001      1  5051.21   30      NaN
2          1   657200  2001      2  5050.51   58      NaN
3          1   657200  2001      3  5050.71   89      NaN
4          1   657200  2001      4  5051.53  119      NaN
...      ...      ...   ...    ...      ...  ...      ...
59068    203  1799675  2023     10      NaN  289  175.356
59069    203  1799675  2023     10  5606.59  303      NaN
59070    203  1799675  2023     11  5606.73  333      NaN
59071    203  1799675  2023     12  5603.19  364      NaN
59072    203  1799675  2024      1  5603.23   30      NaN

[59073 rows x 7 columns]

In [25]:
for (pid, year), group in Y.groupby(["point_id", "Year"]):
    print(group)
    
    
    # Y_dict[(pid, year)] = group[["doy", "somsc", "cgrain"]].to_numpy()

       runid point_id  Year  month  somsc  doy   cgrain
29973    104  1773513  2000     10    NaN  289  162.738
       runid point_id  Year  month    somsc  doy   cgrain
29974    104  1773513  2001      1  4311.61   30      NaN
29975    104  1773513  2001      2  4310.76   58      NaN
29976    104  1773513  2001      3  4310.83   89      NaN
29977    104  1773513  2001      4  4311.45  119      NaN
29978    104  1773513  2001      5  4313.33  150      NaN
29979    104  1773513  2001      6  4274.77  180      NaN
29980    104  1773513  2001      7  4267.10  211      NaN
29981    104  1773513  2001      8  4266.48  242      NaN
29982    104  1773513  2001      9  4264.64  272      NaN
29983    104  1773513  2001     10      NaN  289  138.956
29984    104  1773513  2001     10  4261.90  303      NaN
29985    104  1773513  2001     11  4253.73  333      NaN
29986    104  1773513  2001     12  4239.40  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
29987    104  1773513  2002      1  4234.75   30      NaN
29988    104  1773513  2002      2  4233.13   58      NaN
29989    104  1773513  2002      3  4232.55   89      NaN
29990    104  1773513  2002      4  4232.66  119      NaN
29991    104  1773513  2002      5  4233.67  150      NaN
29992    104  1773513  2002      6  4203.80  180      NaN
29993    104  1773513  2002      7  4192.77  211      NaN
29994    104  1773513  2002      8  4193.29  242      NaN
29995    104  1773513  2002      9  4192.86  272      NaN
29996    104  1773513  2002     10      NaN  289  106.714
29997    104  1773513  2002     10  4191.90  303      NaN
29998    104  1773513  2002     11  4185.51  333      NaN
29999    104  1773513  2002     12  4172.30  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
30000    104  1773513  2003      1  4167.36   30      NaN
30001    104  1773513  2003      2  4165.06   58      NaN
30002    104  1773513  2003      3  4164.12   89      NaN
30003    104  1773513  2003      4  4164.03  119      NaN
30004    104  1773513  2003      5  4165.05  150      NaN
30005    104  1773513  2003      6  4137.44  180      NaN
30006    104  1773513  2003      7  4131.33  211      NaN
30007    104  1773513  2003      8  4131.53  242      NaN
30008    104  1773513  2003      9  4128.59  272      NaN
30009    104  1773513  2003     10      NaN  289  162.457
30010    104  1773513  2003     10  4125.55  303      NaN
30011    104  1773513  2003     11  4122.44  333      NaN
30012    104  1773513  2003     12  4112.42  364      NaN
       runid point_id  Year  month    somsc  doy  cgrain
30013    104  1773513  2004      1  4109.54   30     NaN
30014    104  1773513  2004      2  4108.74   58     NaN
30015    104  1773513  2004      3  4108.92   89     NaN
30016    104  1773513  2004      4  4109.87  119     NaN
30017    104  1773513  2004      5  4112.47  150     NaN
30018    104  1773513  2004      6  4115.12  180     NaN
30019    104  1773513  2004      7  4111.57  211     NaN
30020    104  1773513  2004      8  4104.40  242     NaN
30021    104  1773513  2004      9  4097.03  272     NaN
30022    104  1773513  2004     10  4089.66  303     NaN
30023    104  1773513  2004     11  4086.24  333     NaN
30024    104  1773513  2004     12  4072.32  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30025    104  1773513  2005      1  4065.99   30     NaN
30026    104  1773513  2005      2  4062.03   58     NaN
30027    104  1773513  2005      3  4059.30   89     NaN
30028    104  1773513  2005      4  4057.05  119     NaN
30029    104  1773513  2005      5  4053.44  150     NaN
30030    104  1773513  2005      6  4049.20  180     NaN
30031    104  1773513  2005      7  4042.89  211     NaN
30032    104  1773513  2005      8  4036.19  242     NaN
30033    104  1773513  2005      9  4029.68  272     NaN
30034    104  1773513  2005     10  4023.30  303     NaN
30035    104  1773513  2005     11  4019.80  333     NaN
30036    104  1773513  2005     12  4007.28  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30037    104  1773513  2006      1  4001.46   30     NaN
30038    104  1773513  2006      2  3997.58   58     NaN
30039    104  1773513  2006      3  3994.98   89     NaN
30040    104  1773513  2006      4  3992.66  119     NaN
30041    104  1773513  2006      5  3989.05  150     NaN
30042    104  1773513  2006      6  3984.88  180     NaN
30043    104  1773513  2006      7  3978.88  211     NaN
30044    104  1773513  2006      8  3972.56  242     NaN
30045    104  1773513  2006      9  3966.27  272     NaN
30046    104  1773513  2006     10  3960.75  303     NaN
30047    104  1773513  2006     11  3958.04  333     NaN
30048    104  1773513  2006     12  3946.88  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30049    104  1773513  2007      1  3940.52   30     NaN
30050    104  1773513  2007      2  3936.71   58     NaN
30051    104  1773513  2007      3  3934.27   89     NaN
30052    104  1773513  2007      4  3931.70  119     NaN
30053    104  1773513  2007      5  3928.90  150     NaN
30054    104  1773513  2007      6  3923.93  180     NaN
30055    104  1773513  2007      7  3917.87  211     NaN
30056    104  1773513  2007      8  3911.74  242     NaN
30057    104  1773513  2007      9  3905.45  272     NaN
30058    104  1773513  2007     10  3899.73  303     NaN
30059    104  1773513  2007     11  3895.74  333     NaN
30060    104  1773513  2007     12  3883.99  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30061    104  1773513  2008      1  3878.16   30     NaN
30062    104  1773513  2008      2  3874.60   58     NaN
30063    104  1773513  2008      3  3872.20   89     NaN
30064    104  1773513  2008      4  3870.25  119     NaN
30065    104  1773513  2008      5  3867.15  150     NaN
30066    104  1773513  2008      6  3863.27  180     NaN
30067    104  1773513  2008      7  3857.46  211     NaN
30068    104  1773513  2008      8  3851.50  242     NaN
30069    104  1773513  2008      9  3845.67  272     NaN
30070    104  1773513  2008     10  3840.07  303     NaN
30071    104  1773513  2008     11  3837.00  333     NaN
30072    104  1773513  2008     12  3835.52  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30073    104  1773513  2009      1  3834.60   30     NaN
30074    104  1773513  2009      2  3833.78   58     NaN
30075    104  1773513  2009      3  3832.99   89     NaN
30076    104  1773513  2009      4  3831.88  119     NaN
30077    104  1773513  2009      5  3830.25  150     NaN
30078    104  1773513  2009      6  3826.37  180     NaN
30079    104  1773513  2009      7  3820.92  211     NaN
30080    104  1773513  2009      8  3814.89  242     NaN
30081    104  1773513  2009      9  3808.80  272     NaN
30082    104  1773513  2009     10  3803.59  303     NaN
30083    104  1773513  2009     11  3801.35  333     NaN
30084    104  1773513  2009     12  3799.80  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30085    104  1773513  2010      1  3798.83   30     NaN
30086    104  1773513  2010      2  3798.01   58     NaN
30087    104  1773513  2010      3  3797.25   89     NaN
30088    104  1773513  2010      4  3796.27  119     NaN
30089    104  1773513  2010      5  3794.09  150     NaN
30090    104  1773513  2010      6  3790.08  180     NaN
30091    104  1773513  2010      7  3784.36  211     NaN
30092    104  1773513  2010      8  3778.49  242     NaN
30093    104  1773513  2010      9  3772.82  272     NaN
30094    104  1773513  2010     10  3767.23  303     NaN
30095    104  1773513  2010     11  3764.14  333     NaN
30096    104  1773513  2010     12  3762.76  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30097    104  1773513  2011      1  3761.81   30     NaN
30098    104  1773513  2011      2  3761.01   58     NaN
30099    104  1773513  2011      3  3760.25   89     NaN
30100    104  1773513  2011      4  3759.39  119     NaN
30101    104  1773513  2011      5  3757.92  150     NaN
30102    104  1773513  2011      6  3754.30  180     NaN
30103    104  1773513  2011      7  3748.99  211     NaN
30104    104  1773513  2011      8  3743.02  242     NaN
30105    104  1773513  2011      9  3737.34  272     NaN
30106    104  1773513  2011     10  3732.39  303     NaN
30107    104  1773513  2011     11  3729.64  333     NaN
30108    104  1773513  2011     12  3728.11  364     NaN
       runid point_id  Year  month    somsc  doy   cgrain
30109    104  1773513  2012      1  3727.15   30      NaN
30110    104  1773513  2012      2  3726.36   58      NaN
30111    104  1773513  2012      3  3725.63   89      NaN
30112    104  1773513  2012      4  3723.89  119      NaN
30113    104  1773513  2012      5  3722.02  150      NaN
30114    104  1773513  2012      6  3700.66  180      NaN
30115    104  1773513  2012      7  3696.73  211      NaN
30116    104  1773513  2012      8  3694.37  242      NaN
30117    104  1773513  2012      9  3691.48  272      NaN
30118    104  1773513  2012     10  3689.48  303      NaN
30119    104  1773513  2012     10      NaN  305  202.126
30120    104  1773513  2012     11  3688.27  333      NaN
30121    104  1773513  2012     12  3691.05  364      NaN
       runid point_id  Year  month    somsc  doy  cgrain
30122    104  1773513  2013      1  3691.88   30     NaN
30123    104  1773513  2013      2  3692.58   58     NaN
30124    104  1773513  2013      3  3693.33   89     NaN
30125    104  1773513  2013      4  3694.13  119     NaN
30126    104  1773513  2013      5  3695.32  150     NaN
30127    104  1773513  2013      6  3691.95  180     NaN
30128    104  1773513  2013      7  3689.69  211     NaN
30129    104  1773513  2013      8  3687.51  242     NaN
30130    104  1773513  2013      9  3686.51  272     NaN
30131    104  1773513  2013     10  3685.36  303     NaN
30132    104  1773513  2013     11      NaN  305  328.14
30133    104  1773513  2013     11  3684.26  333     NaN
30134    104  1773513  2013     12  3700.11  364     NaN
       runid point_id  Year  month    somsc  doy   cgrain
30135    104  1773513  2014      1  3704.16   30      NaN
30136    104  1773513  2014      2  3706.99   58      NaN
30137    104  1773513  2014      3  3709.39   89      NaN
30138    104  1773513  2014      4  3711.56  119      NaN
30139    104  1773513  2014      5  3714.52  150      NaN
30140    104  1773513  2014      6  3724.72  180      NaN
30141    104  1773513  2014      7  3724.83  211      NaN
30142    104  1773513  2014      8  3725.12  242      NaN
30143    104  1773513  2014      9  3725.10  272      NaN
30144    104  1773513  2014     10  3724.30  303      NaN
30145    104  1773513  2014     11      NaN  305  248.159
30146    104  1773513  2014     11  3723.52  333      NaN
30147    104  1773513  2014     12  3739.84  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
30148    104  1773513  2015      1  3741.43   30      NaN
30149    104  1773513  2015      2  3742.65   58      NaN
30150    104  1773513  2015      3  3743.78   89      NaN
30151    104  1773513  2015      4  3744.99  119      NaN
30152    104  1773513  2015      5  3746.77  150      NaN
30153    104  1773513  2015      6  3753.32  180      NaN
30154    104  1773513  2015      7  3751.99  211      NaN
30155    104  1773513  2015      8  3750.74  242      NaN
30156    104  1773513  2015      9  3748.68  272      NaN
30157    104  1773513  2015     10  3747.42  303      NaN
30158    104  1773513  2015     11      NaN  305  234.133
30159    104  1773513  2015     11  3747.02  333      NaN
30160    104  1773513  2015     12  3770.97  364      NaN
       runid point_id  Year  month    somsc  doy  cgrain
30161    104  1773513  2016      1  3776.72   30     NaN
30162    104  1773513  2016      2  3780.16   58     NaN
30163    104  1773513  2016      3  3783.03   89     NaN
30164    104  1773513  2016      4  3786.19  119     NaN
30165    104  1773513  2016      5  3789.84  150     NaN
30166    104  1773513  2016      6  3793.63  180     NaN
30167    104  1773513  2016      7  3795.72  211     NaN
30168    104  1773513  2016      8  3793.00  242     NaN
30169    104  1773513  2016      9  3788.84  272     NaN
30170    104  1773513  2016     10  3784.91  303     NaN
30171    104  1773513  2016     11  3802.31  333     NaN
30172    104  1773513  2016     12  3795.14  364     NaN
       runid point_id  Year  month    somsc  doy   cgrain
30173    104  1773513  2017      1  3792.59   30      NaN
30174    104  1773513  2017      2  3790.95   58      NaN
30175    104  1773513  2017      3  3789.62   89      NaN
30176    104  1773513  2017      4  3788.54  119      NaN
30177    104  1773513  2017      5  3787.19  150      NaN
30178    104  1773513  2017      6  3785.85  180      NaN
30179    104  1773513  2017      7      NaN  184  161.921
30180    104  1773513  2017      7  3783.98  211      NaN
30181    104  1773513  2017      8  3790.57  242      NaN
30182    104  1773513  2017      9  3791.15  272      NaN
30183    104  1773513  2017     10  3789.55  303      NaN
30184    104  1773513  2017     11  3809.52  333      NaN
30185    104  1773513  2017     12  3804.61  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
30186    104  1773513  2018      1  3802.18   30      NaN
30187    104  1773513  2018      2  3800.59   58      NaN
30188    104  1773513  2018      3  3799.37   89      NaN
30189    104  1773513  2018      4  3798.36  119      NaN
30190    104  1773513  2018      5  3797.42  150      NaN
30191    104  1773513  2018      6  3795.77  180      NaN
30192    104  1773513  2018      7      NaN  184  111.117
30193    104  1773513  2018      7  3793.62  211      NaN
30194    104  1773513  2018      8  3804.99  242      NaN
30195    104  1773513  2018      9  3806.96  272      NaN
30196    104  1773513  2018     10  3804.82  303      NaN
30197    104  1773513  2018     11  3824.47  333      NaN
30198    104  1773513  2018     12  3818.83  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
30199    104  1773513  2019      1  3815.99   30      NaN
30200    104  1773513  2019      2  3814.10   58      NaN
30201    104  1773513  2019      3  3812.75   89      NaN
30202    104  1773513  2019      4  3811.65  119      NaN
30203    104  1773513  2019      5  3810.35  150      NaN
30204    104  1773513  2019      6  3808.94  180      NaN
30205    104  1773513  2019      7      NaN  184  98.5288
30206    104  1773513  2019      7  3806.96  211      NaN
30207    104  1773513  2019      8  3828.77  242      NaN
30208    104  1773513  2019      9  3829.69  272      NaN
30209    104  1773513  2019     10  3827.31  303      NaN
30210    104  1773513  2019     11  3825.38  333      NaN
30211    104  1773513  2019     12  3824.62  364      NaN
       runid point_id  Year  month    somsc  doy  cgrain
30212    104  1773513  2020      1  3823.99   30     NaN
30213    104  1773513  2020      2  3823.44   58     NaN
30214    104  1773513  2020      3  3822.88   89     NaN
30215    104  1773513  2020      4  3821.73  119     NaN
30216    104  1773513  2020      5  3820.79  150     NaN
30217    104  1773513  2020      6  3820.10  180     NaN
30218    104  1773513  2020      7      NaN  184  104.85
30219    104  1773513  2020      7  3819.31  211     NaN
30220    104  1773513  2020      8  3828.24  242     NaN
30221    104  1773513  2020      9  3830.94  272     NaN
30222    104  1773513  2020     10  3829.71  303     NaN
30223    104  1773513  2020     11  3893.83  333     NaN
30224    104  1773513  2020     12  3883.27  364     NaN
       runid point_id  Year  month    somsc  doy  cgrain
30225    104  1773513  2021      1  3876.68   30     NaN
30226    104  1773513  2021      2  3872.65   58     NaN
30227    104  1773513  2021      3  3870.02   89     NaN
30228    104  1773513  2021      4  3868.00  119     NaN
30229    104  1773513  2021      5  3865.77  150     NaN
30230    104  1773513  2021      6  3863.68  180     NaN
30231    104  1773513  2021      7  3859.62  211     NaN
30232    104  1773513  2021      8  3854.73  242     NaN
30233    104  1773513  2021      9  3852.41  272     NaN
30234    104  1773513  2021     10  3849.67  303     NaN
30235    104  1773513  2021     11  3838.73  333     NaN
30236    104  1773513  2021     12  3822.14  364     NaN
       runid point_id  Year  month    somsc  doy   cgrain
30237    104  1773513  2022      1  3815.29   30      NaN
30238    104  1773513  2022      2  3811.19   58      NaN
30239    104  1773513  2022      3  3808.44   89      NaN
30240    104  1773513  2022      4  3806.51  119      NaN
30241    104  1773513  2022      5  3804.49  150      NaN
30242    104  1773513  2022      6  3802.95  180      NaN
30243    104  1773513  2022      7      NaN  184  146.175
30244    104  1773513  2022      7  3801.48  211      NaN
30245    104  1773513  2022      8  3813.52  242      NaN
30246    104  1773513  2022      9  3817.47  272      NaN
30247    104  1773513  2022     10  3815.85  303      NaN
30248    104  1773513  2022     11  3832.99  333      NaN
30249    104  1773513  2022     12  3820.34  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
30250    104  1773513  2023      1  3813.70   30      NaN
30251    104  1773513  2023      2  3809.60   58      NaN
30252    104  1773513  2023      3  3806.79   89      NaN
30253    104  1773513  2023      4  3804.51  119      NaN
30254    104  1773513  2023      5  3801.90  150      NaN
30255    104  1773513  2023      6  3757.09  180      NaN
30256    104  1773513  2023      7  3743.79  211      NaN
30257    104  1773513  2023      8  3739.75  242      NaN
30258    104  1773513  2023      9  3736.85  272      NaN
30259    104  1773513  2023     10      NaN  289  141.607
30260    104  1773513  2023     10  3735.58  303      NaN
30261    104  1773513  2023     11  3738.02  333      NaN
30262    104  1773513  2023     12  3737.21  364      NaN
       runid point_id  Year  month    somsc  doy  cgrain
30263    104  1773513  2024      1  3737.59   30     NaN
       runid point_id  Year  month  somsc  doy   cgrain
30264    105  1773576  2000     10    NaN  289  163.772
       runid point_id  Year  month    somsc  doy   cgrain
30265    105  1773576  2001      1  3551.20   30      NaN
30266    105  1773576  2001      2  3550.64   58      NaN
30267    105  1773576  2001      3  3550.96   89      NaN
30268    105  1773576  2001      4  3551.82  119      NaN
30269    105  1773576  2001      5  3554.18  150      NaN
30270    105  1773576  2001      6  3518.10  180      NaN
30271    105  1773576  2001      7  3512.79  211      NaN
30272    105  1773576  2001      8  3513.28  242      NaN
30273    105  1773576  2001      9  3513.17  272      NaN
30274    105  1773576  2001     10      NaN  289  119.383
30275    105  1773576  2001     10  3511.60  303      NaN
30276    105  1773576  2001     11  3501.49  333      NaN
30277    105  1773576  2001     12  3486.66  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain
30278    105  1773576  2002      1  3481.80   30      NaN
30279    105  1773576  2002      2  3480.28   58      NaN
30280    105  1773576  2002      3  3479.78   89      NaN
30281    105  1773576  2002      4  3479.94  119      NaN
30282    105  1773576  2002      5  3480.92  150      NaN
30283    105  1773576  2002      6  3452.60  180      NaN
30284    105  1773576  2002      7  3443.07  211      NaN
30285    105  1773576  2002      8  3444.06  242      NaN
30286    105  1773576  2002      9  3444.51  272      NaN
30287    105  1773576  2002     10      NaN  289  139.885
30288    105  1773576  2002     10  3442.66  303      NaN
30289    105  1773576  2002     11  3435.88  333      NaN
30290    105  1773576  2002     12  3424.65  364      NaN
       runid point_id  Year  month    somsc  doy   cgrain

In [29]:
# Ensure both point_id and Year are integers everywhere
df["point_id"] = df["point_id"].astype(int)
df["Year"] = df["Year"].astype(int)
Y["point_id"] = Y["point_id"].astype(int)
Y["Year"] = Y["Year"].astype(int)

# If mapping already exists as np.array of strings, convert it
mapping = np.array([[int(pid), int(year)] for pid, year in mapping])

# Build dictionary keyed by (point_id, Year)
Y_dict = {}
for (pid, year), group in Y.groupby(["point_id", "Year"]):
    Y_dict[(pid, year)] = group[["month", "doy", "somsc", "cgrain"]].to_numpy()

# Align Y to mapping
somsc_list = []
cgrain_list = []
for pid, year in mapping:
    if (pid, year) in Y_dict:
        data = Y_dict[(pid, year)]
        

        somsc_array = np.full(12, np.nan, dtype=np.float64)
        
        # The 'data' array has columns: 0=month, 1=doy, 2=somsc, 3=cgrain
        
        # 1a. Create a boolean mask to filter rows where 'somsc' (column index 2) is NOT NaN
        valid_somsc_mask = ~np.isnan(data[:, 2])
        
        # 1b. Filter the data to include only rows with valid somsc values
        valid_data = data[valid_somsc_mask]
        
        # 1c. Get the 0-indexed positions for assignment: month (column 0) - 1
        # We must ensure the indices are integers
        indices = valid_data[:, 0].astype(int) - 1
        
        # 1d. Get the corresponding somsc values (column 2)
        values = valid_data[:, 2]
        
        # 1e. Use advanced NumPy indexing for vectorized assignment
        # This is much faster than iterating row by row.
        # Note: If there are multiple somsc values for the same month, 
        # the last value encountered in the 'data' array (due to sorting in Y_dict) will be used.
        if indices.size > 0:
            somsc_array[indices] = values

            # 2. cgrain value: Must be a single number (no NaNs allowed in the source data)
        # Extract all cgrain values for this year (column index 3)
        cgrain_values = data[:, 3]
        
        # Filter out NaN values to find the single valid cgrain number
        valid_cgrain = cgrain_values[~np.isnan(cgrain_values)]
        
        # Append the results
        if valid_cgrain.size > 0:
            # Append the single annual cgrain value (the user guarantees it's unique/present)
            cgrain_list.append(valid_cgrain[0]) 
            
            # Append the 12-element monthly somsc array
            somsc_list.append(somsc_array)
        else:
            # Handle the case where Cgrain is unexpectedly missing (use NaN as a fallback)
            # print(f"Warning: cgrain value is missing for point_id {pid}, Year {year}. Appending NaN.")
            somsc_list.append(somsc_array)
            cgrain_list.append(np.nan)
        

    else:
        print(f"Missing data for point_id {pid}, Year {year}")
        somsc_list.append(np.empty((0, 2)))
        cgrain_list.append(np.empty((0, 2)))


# Convert lists to final NumPy arrays
final_somsc_array = np.array(somsc_list)
final_cgrain_array = np.array(cgrain_list)

# --- RESULTS ---
print("\n--- Final Results ---")
print("Mapping length:", len(mapping))
print("SOMSC List length:", len(somsc_list))
print("CGRAIN List length:", len(cgrain_list))

print(f"\nFinal SOMSC Array (Shape: {final_somsc_array.shape}):")
print(final_somsc_array)

print(f"\nFinal CGRAIN Array (Shape: {final_cgrain_array.shape}):")
print(final_cgrain_array)

--- Final Results ---
Mapping length: 5075
SOMSC List length: 5075
CGRAIN List length: 5075

Final SOMSC Array (Shape: (5075, 12)):
[[    nan     nan     nan ...     nan     nan     nan]
 [4311.61 4310.76 4310.83 ... 4261.9  4253.73 4239.4 ]
 [4234.75 4233.13 4232.55 ... 4191.9  4185.51 4172.3 ]
 ...
 [3876.55 3871.91 3868.79 ... 3875.65 3896.44 3883.99]
 [3876.74 3872.25 3869.08 ... 3792.01 3794.09 3791.78]
 [3791.75     nan     nan ...     nan     nan     nan]]

Final CGRAIN Array (Shape: (5075,)):
[162.738 138.956 106.714 ... 168.522 176.591     nan]

In [52]:
data_dict = {
    "somsc": final_somsc_array,
    "cgrain": final_cgrain_array,
}

np.save(os.path.join(PROCESSED_DIR, "daycent_outputs.npy"), data_dict, allow_pickle=True)

Empty DataFrame
Columns: [runid, point_id, Year, month, somsc, doy, cgrain]
Index: []

In [63]:
idx = 0
Y[Y['point_id'] == '1773513'][Y['Year'] == mapping[idx,1]]

/tmp/ipykernel_27974/3854136065.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Y[Y['point_id'] == '1773513'][Y['Year'] == mapping[idx,1]]

Empty DataFrame
Columns: [runid, point_id, Year, month, somsc, doy, cgrain]
Index: []

In [61]:
Y

       runid  point_id  Year  month    somsc  doy   cgrain
0          1    657200  2000     10      NaN  289  170.656
1          1    657200  2001      1  5051.21   30      NaN
2          1    657200  2001      2  5050.51   58      NaN
3          1    657200  2001      3  5050.71   89      NaN
4          1    657200  2001      4  5051.53  119      NaN
...      ...       ...   ...    ...      ...  ...      ...
59068    203   1799675  2023     10      NaN  289  175.356
59069    203   1799675  2023     10  5606.59  303      NaN
59070    203   1799675  2023     11  5606.73  333      NaN
59071    203   1799675  2023     12  5603.19  364      NaN
59072    203   1799675  2024      1  5603.23   30      NaN

[59073 rows x 7 columns]